authentication video + task
lbrezgin/test-guru pull request #13
Opened 2023-12-05 10:41 UTC by lbrezgin

2023-12-05 16:46 UTC, BubuntuClu requested changes

2023-12-05 16:46 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    unless current_user
у тебя уже есть такая проверка на 7ой строке. зачем ее еще раз вызывать?
вполне нормально под 7ю строчку добавить сохранение пути. зато не делаешь лишнний колбэк, который ты везде дергаешь

2023-12-05 16:46 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!
что будет если этот колбэк прописать в родительском контроллере, а не писать в каждом дочернем?

2023-12-05 16:46 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if session[:return_to].present?
если там будет пусто, то его никуда не перекинем? плохое решение
`redirect_to session[:return_to] || root_path` и в этом случае `if` не нужен

2023-12-05 16:46 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @user = current_user
что возвращает метод `current_user`? ты просто перекладываешь пользователя в еще одну переменную, что бы что? используй сразу `current_user` там где тебе нужен пользователь.

метод `set_user` уже не нужен и колбэк для него

2023-12-05 16:46 UTC, BubuntuClu commented on app/views/sessions/_form.html.erb
> +  <% if flash[:alert] %>
>Создайте хэлпер для flash сообщений

это не хэлпер. хэлпер это файл в папке `helpers`

у тебя может быть несколько ключей для флэшей, не только `alert`, нужно выводить их все

2023-12-05 16:46 UTC, BubuntuClu commented on config/routes.rb
> +  get 'users/new'
эти роуты дублируют роуты ниже

2023-12-05 16:46 UTC, BubuntuClu commented on db/schema.rb
>      t.string "email"
надо добавить уникальный индекс на поле почты, записи можно создать напрямую в БД, не через приложение

2023-12-06 17:22 UTC, BubuntuClu requested changes

2023-12-06 17:22 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test.author = current_user
нет, еще думай.
https://github.com/lbrezgin/test-guru/blob/main/app/models/user.rb вот тут у тебя есть подсказки. ты создать объект в одну строку можешь, не надо делать костыль в виде отдельного присваивание автора

2023-12-06 17:22 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +  def flash_helper(key, text)
этот хэлпер нужен для вывода флэша. то есть то, что используется во вьюхах.

вот в этом файле app/views/sessions/_form.html.erb ты вызывать этот метод должен

2023-12-06 17:22 UTC, BubuntuClu commented on app/views/sessions/_form.html.erb
> +  <% if flash[:alert] %>
тут ничего не изменилось. весь этот код надо в хэлпер перенести. и сделать так чтобы он выводил все флэши за один вызов метода

2023-12-07 07:05 UTC, BubuntuClu requested changes

2023-12-07 07:05 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +    if flash[key] && key == :alert
представь что тебе нужно вывести флэши с ключами `info`/`notice`/`warning`.

получается на вьюхе ты будешь иметь такой код
```
<%= flash_helper(:alert) %>
<%= flash_helper(:info) %>
<%= flash_helper(:notice) %>
<%= flash_helper(:warning) %>
```

и еще в этом методе тебе надо будет лестницу из `if` сделать чтобы все ключи обработать. выглядит очень запарно.

почему бы просто не перебрать все что есть во флэше и не вывести на страницу?

не нужен параметр в метод. сделай `flash.map...` и правильно отобрази результат

2023-12-07 07:05 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = current_user.created_tests.build(test_params)
да, вот так правильно

2023-12-07 17:03 UTC, BubuntuClu commented on app/helpers/sessions_helper.rb
> +      content_tag :p, flash.now[key], class: "flash #{key}"
`flash.now[key]` а это зачем?  утебя ведь есть `value` где находится текст сообщения

2023-12-07 17:24 UTC, leobrezgin commented on app/helpers/sessions_helper.rb
> +      content_tag :p, flash.now[key], class: "flash #{key}"
поправил

2023-12-07 17:25 UTC, merged